# Site settings
title: "Spencer Long: Future Data Scientist"
description: A blog about Spencer Long
baseurl: "/website" # the subpath of your site, e.g. /blog
#url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Spencer Long
user_description: "<P align=left>I have spent the past 4 years conducting number crunching and database management for research/business purposes, and I am keen to continue developing my career in the field of Data Science. I have always been a numbers person, with exceptional mathematics and computer skills. Statistical significance, A/B testing, and data-driven optimization are the rhythm of the drumbeat I march to. <br><br>
As much as I’m into data manipulation, it’s the data analysis that really gets me going. I like to explore the relationships between numbers, and translate digits and spreadsheets into stories. In the age of big data, these stories become actionable solutions and strategies for businesses, and I take pride in my ability to make data accessible to both executives and the uninitiated. <br><br>
On a personal level, I am detail-oriented, organized, and precise in my work; the only things cleaner than my desk are my spreadsheets, and let me tell you, I maintain a desk that displays my Curiosity rover, Apollo Lunar Module, Discovery space shuttle, and bachelor’s degree proudly. I have strong communication skills with a knack for clear and illuminating presentation. I’m comfortable on my own facing the numbers, but I really enjoy being part of a motivated team of smart people.</P>
"


user_title: Future Data Scientist
email: spencer42long@gmail.com
#twitter_username: lorem_ipsum
github_username:  Spencer-Long
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
